[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "endstone-antispam"
version = "0.0.1"
description = "Plugin AntiSpam by Kyel0"

[project.entry-points."endstone"]
antispam = "endstone_antispam:AntiSpam"